#!/usr/bin python
# -*- coding: utf-8 -*-
import xlrd 
data = xlrd.open_workbook('/Users/yang.gao/Downloads/bloomberg_20171219.xlsx') # 打开xls文件
table = data.sheets()[0] # 打开第一张表
nrows = table.nrows # 获取表的行数
for i in range(nrows): # 循环逐行打印
  if i == 0: # 
  continue
  print table.row_values(i)[:nrows] # 取前十三列
